-- PitStop Assistant — schéma Supabase multi-saison
-- Appliquer via `python -m app.data_pipeline.migrate`.
-- Ne pas exécuter de données réelles dans Git.

CREATE TABLE IF NOT EXISTS seasons (
    season    SMALLINT PRIMARY KEY CHECK (season >= 1950),
    label     TEXT NOT NULL,
    start_date DATE
);

CREATE TABLE IF NOT EXISTS drivers (
    driver_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT NOT NULL,
    code       TEXT,
    nationality TEXT
);

CREATE TABLE IF NOT EXISTS constructors (
    constructor_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           TEXT NOT NULL,
    code           TEXT,
    nationality    TEXT
);

CREATE TABLE IF NOT EXISTS races (
    race_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season       SMALLINT NOT NULL REFERENCES seasons (season),
    round_number SMALLINT NOT NULL CHECK (round_number > 0),
    race_key     TEXT NOT NULL,
    name         TEXT NOT NULL,
    circuit_name TEXT,
    race_date    DATE,
    url          TEXT,
    CONSTRAINT races_race_id_season_key UNIQUE (race_id, season),
    CONSTRAINT races_season_round_key UNIQUE (season, round_number),
    CONSTRAINT races_season_race_key UNIQUE (season, race_key)
);

CREATE TABLE IF NOT EXISTS results (
    result_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season          SMALLINT NOT NULL,
    race_id         BIGINT NOT NULL,
    driver_id       BIGINT NOT NULL REFERENCES drivers (driver_id),
    constructor_id  BIGINT REFERENCES constructors (constructor_id),
    driver_number   INTEGER CHECK (driver_number IS NULL OR driver_number >= 0),
    grid_position   INTEGER CHECK (grid_position IS NULL OR grid_position >= 0),
    finish_position INTEGER CHECK (finish_position IS NULL OR finish_position >= 0),
    points          NUMERIC(6, 2) NOT NULL DEFAULT 0,
    laps            INTEGER CHECK (laps IS NULL OR laps >= 0),
    status          TEXT,
    fastest_lap_rank INTEGER,
    CONSTRAINT results_race_fk FOREIGN KEY (race_id, season)
        REFERENCES races (race_id, season),
    CONSTRAINT results_race_driver_key UNIQUE (season, race_id, driver_id)
);

CREATE TABLE IF NOT EXISTS standings (
    standing_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season         SMALLINT NOT NULL REFERENCES seasons (season),
    race_id        BIGINT,
    driver_id      BIGINT NOT NULL REFERENCES drivers (driver_id),
    constructor_id BIGINT REFERENCES constructors (constructor_id),
    driver_number  INTEGER,
    position       INTEGER NOT NULL CHECK (position > 0),
    points         NUMERIC(6, 2) NOT NULL DEFAULT 0,
    wins           INTEGER NOT NULL DEFAULT 0 CHECK (wins >= 0),
    CONSTRAINT standings_race_fk FOREIGN KEY (race_id, season)
        REFERENCES races (race_id, season),
    CONSTRAINT standings_race_driver_key UNIQUE (season, race_id, driver_id)
);

CREATE TABLE IF NOT EXISTS laps (
    lap_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season      SMALLINT NOT NULL,
    race_id     BIGINT NOT NULL,
    driver_id   BIGINT NOT NULL REFERENCES drivers (driver_id),
    lap_number  INTEGER NOT NULL CHECK (lap_number > 0),
    lap_time_ms INTEGER CHECK (lap_time_ms IS NULL OR lap_time_ms >= 0),
    compound    TEXT,
    tyre_life   INTEGER CHECK (tyre_life IS NULL OR tyre_life >= 0),
    pit_in_lap  BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT laps_race_fk FOREIGN KEY (race_id, season)
        REFERENCES races (race_id, season),
    CONSTRAINT laps_race_driver_lap_key UNIQUE (season, race_id, driver_id, lap_number)
);

CREATE TABLE IF NOT EXISTS pit_stops (
    pit_stop_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season       SMALLINT NOT NULL,
    race_id      BIGINT NOT NULL,
    driver_id    BIGINT NOT NULL REFERENCES drivers (driver_id),
    lap_number   INTEGER NOT NULL CHECK (lap_number > 0),
    stop_number  INTEGER NOT NULL DEFAULT 1 CHECK (stop_number > 0),
    pit_in_ms    INTEGER CHECK (pit_in_ms IS NULL OR pit_in_ms >= 0),
    pit_out_ms   INTEGER CHECK (pit_out_ms IS NULL OR pit_out_ms >= 0),
    duration_ms  INTEGER CHECK (duration_ms IS NULL OR duration_ms >= 0),
    compound     TEXT,
    CONSTRAINT pit_stops_race_fk FOREIGN KEY (race_id, season)
        REFERENCES races (race_id, season),
    CONSTRAINT pit_stops_race_driver_lap_stop_key
        UNIQUE (season, race_id, driver_id, lap_number, stop_number)
);

CREATE TABLE IF NOT EXISTS tire_stints (
    stint_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season       SMALLINT NOT NULL,
    race_id      BIGINT NOT NULL,
    driver_id    BIGINT NOT NULL REFERENCES drivers (driver_id),
    stint_number INTEGER NOT NULL CHECK (stint_number > 0),
    compound     TEXT,
    tyre_life    INTEGER CHECK (tyre_life IS NULL OR tyre_life >= 0),
    start_lap    INTEGER CHECK (start_lap IS NULL OR start_lap >= 0),
    end_lap      INTEGER CHECK (end_lap IS NULL OR end_lap >= 0),
    pit_in_lap   INTEGER,
    pit_out_lap  INTEGER,
    CONSTRAINT tire_stints_race_fk FOREIGN KEY (race_id, season)
        REFERENCES races (race_id, season),
    CONSTRAINT tire_stints_race_driver_stint_key
        UNIQUE (season, race_id, driver_id, stint_number)
);

CREATE TABLE IF NOT EXISTS logs (
    log_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id  UUID NOT NULL UNIQUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    question    TEXT,
    answer      TEXT,
    category    TEXT,
    latency_ms  INTEGER CHECK (latency_ms IS NULL OR latency_ms >= 0),
    feedback    TEXT CHECK (feedback IS NULL OR feedback IN ('up', 'down')),
    agent_trace JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_races_season_round ON races (season, round_number);
CREATE INDEX IF NOT EXISTS idx_results_season_driver ON results (season, driver_id);
CREATE INDEX IF NOT EXISTS idx_results_season_position ON results (season, finish_position);
CREATE INDEX IF NOT EXISTS idx_standings_season_position ON standings (season, position);
CREATE INDEX IF NOT EXISTS idx_laps_season_race_driver ON laps (season, race_id, driver_id);
CREATE INDEX IF NOT EXISTS idx_pit_stops_season_race_driver ON pit_stops (season, race_id, driver_id);
CREATE INDEX IF NOT EXISTS idx_tire_stints_season_race_driver ON tire_stints (season, race_id, driver_id);
CREATE INDEX IF NOT EXISTS idx_logs_created_at ON logs (created_at DESC);

REVOKE ALL ON TABLE
    public.seasons,
    public.drivers,
    public.constructors,
    public.races,
    public.results,
    public.standings,
    public.laps,
    public.pit_stops,
    public.tire_stints
FROM anon, authenticated;

GRANT SELECT ON TABLE
    public.seasons,
    public.drivers,
    public.constructors,
    public.races,
    public.results,
    public.standings,
    public.laps,
    public.pit_stops,
    public.tire_stints
TO anon;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE
    public.seasons,
    public.drivers,
    public.constructors,
    public.races,
    public.results,
    public.standings,
    public.laps,
    public.pit_stops,
    public.tire_stints,
    public.logs
TO service_role;

REVOKE ALL ON TABLE public.logs FROM anon, authenticated;

ALTER TABLE public.seasons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.drivers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.constructors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.races ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.standings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.laps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pit_stops ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tire_stints ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon read seasons" ON public.seasons;
CREATE POLICY "anon read seasons" ON public.seasons FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS "anon read drivers" ON public.drivers;
CREATE POLICY "anon read drivers" ON public.drivers FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS "anon read constructors" ON public.constructors;
CREATE POLICY "anon read constructors" ON public.constructors FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS "anon read races" ON public.races;
CREATE POLICY "anon read races" ON public.races FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS "anon read results" ON public.results;
CREATE POLICY "anon read results" ON public.results FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS "anon read standings" ON public.standings;
CREATE POLICY "anon read standings" ON public.standings FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS "anon read laps" ON public.laps;
CREATE POLICY "anon read laps" ON public.laps FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS "anon read pit stops" ON public.pit_stops;
CREATE POLICY "anon read pit stops" ON public.pit_stops FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS "anon read tire stints" ON public.tire_stints;
CREATE POLICY "anon read tire stints" ON public.tire_stints FOR SELECT TO anon USING (true);
